export const mockData = {
  topCourse: {
    courseInfo: {
      id: 1,
      name: 'Какой-то курс',
      description: 'Описание курса',
      picture: 'https://picsum.photos/600',
      durationOfLessons: '3 - 5',
      startDate: '2019-12-17T10:18:31.755Z',
      theBestForYou: true,
      forAnnounce: true,
      beginnerCourse: true,
      colour: '#d4c5bd',
    },
    courseStats: {
      numberOfLessons: 10,
      finishedLessons: 5,
      numberOfStudents: 1234567,
    },
  },
  stats: {
    todayUsers: 1234567,
    todayUsersTime: 12345678,
    maxStrike: 360,
  },
  bestCourses: [
    {
      courseInfo: {
        id: 1,
        name: 'Какой-то курс',
        description: 'Описание курса',
        picture: 'https://picsum.photos/600',
        durationOfLessons: '3 - 5',
        startDate: '2019-01-17T10:18:31.755Z',
        theBestForYou: true,
        forAnnounce: true,
        beginnerCourse: false,
        colour: '#d4c5bd',
      },
      courseStats: {
        numberOfLessons: 10,
        finishedLessons: 5,
        numberOfStudents: 1234567,
      },
    },
    {
      courseInfo: {
        id: 1,
        name: 'Какой-то курс',
        description: 'Описание курса',
        picture: 'https://picsum.photos/600',
        durationOfLessons: '3 - 5',
        startDate: '2019-12-17T10:18:31.755Z',
        theBestForYou: true,
        forAnnounce: true,
        beginnerCourse: false,
        colour: '#d4c5bd',
      },
      courseStats: {
        numberOfLessons: 10,
        finishedLessons: 5,
        numberOfStudents: 1234567,
      },
    },
    {
      courseInfo: {
        id: 1,
        name: 'Какой-то курс',
        description: 'Описание курса',
        picture: 'https://picsum.photos/600',
        durationOfLessons: '3 - 5',
        startDate: '2019-12-17T10:18:31.755Z',
        theBestForYou: true,
        forAnnounce: true,
        beginnerCourse: false,
        colour: '#d4c5bd',
      },
      courseStats: {
        numberOfLessons: 10,
        finishedLessons: 5,
        numberOfStudents: 1234567,
      },
    },
  ],
  announcement: [
    {
      courseInfo: {
        id: 1,
        name: 'Какой-то курс',
        description: 'Описание курса',
        picture: 'https://picsum.photos/600',
        durationOfLessons: '3 - 5',
        startDate: '2019-12-31T10:18:31.755Z',
        theBestForYou: true,
        forAnnounce: true,
        beginnerCourse: false,
        colour: '#d4c5bd',
      },
      courseStats: {
        numberOfLessons: 10,
        finishedLessons: 5,
        numberOfStudents: 1234567,
      },
    },
  ],
  fastSupport: [
    {
      id: 0,
      name: 'Быстрая помощь',
      trackId: 0,
      forMainPage: true,
      colour: '#d4c5bd',
      duration: '2 минуты',
    },
    {
      id: 0,
      name: 'Быстрая помощь',
      trackId: 0,
      forMainPage: true,
      colour: '#d4c5bd',
      duration: '3 минуты',
    },
    {
      id: 0,
      name: 'Быстрая помощь',
      trackId: 0,
      forMainPage: true,
      colour: '#d4c5bd',
      duration: '4 минуты',
    },
    {
      id: 0,
      name: 'Быстрая помощь',
      trackId: 0,
      forMainPage: true,
      colour: '#d4c5bd',
      duration: '5 минуты',
    },
  ],
  videoAdvice: [
    {
      id: 0,
      name: 'Совет в видео',
      url: '2XO45OyOWjU',
      duration: '17',
      forMainPage: true,
      colour: '#d4c5bd',
    },
    {
      id: 0,
      name: 'Совет в видео',
      url: 'PVsl-iEIKcg',
      duration: '17',
      forMainPage: true,
      colour: '#d4c5bd',
    },
  ],
};
