export enum ActionTypesEnum {
  INPUT = 'INPUT',
  RANGE = 'RANGE',
  CHOICE = 'CHOICE',
  MULTICHOICE = 'MULTICHOICE',
  ACTION = 'ACTION',
  GOTO = 'GOTO',
  CHECKBOX = 'CHECKBOX',
  TIMEPICKER = 'TIMEPICKER',
}
