export enum EventEnum {
  // APP_STARTED = 'APP_STARTED',
  AUTHORIZATION_FINISHED = 'AUTHORIZATION_FINISHED',
  LESSON_FINISHED = 'LESSON_FINISHED',
  COURSE_FINISHED = 'COURSE_FINISHED',
  // ONBOARDING_FINISHED = 'ONBOARDING_FINISHED',
}
