export enum EventDescriptionEnum {
  GO_TO_FIRST_QUIZ = 'GO_TO_FIRST_QUIZ',
  GO_TO_SUBSCRIPTION = 'GO_TO_SUBSCRIPTION',
  GO_TO_HOME = 'GO_TO_HOME',
  GO_TO_PUSHES = 'GO_TO_PUSHES',
  GO_TO_BACK = 'GO_TO_BACK',
  GO_TO_RATING_QUIZ = 'GO_TO_RATING_QUIZ',
  GO_TO_RATING = 'GO_TO_RATING',
  GO_TO_NEWS = 'GO_TO_NEWS',
  GO_TO_NOT_REGISTERED_QUIZ = 'GO_TO_NOT_REGISTERED_QUIZ',
  GO_TO_AUTH = 'GO_TO_AUTH',
  GO_TO_GIFT_QUIZ = 'GO_TO_GIFT_QUIZ',
}
